[mypy]
python_version = 3.14


plugins =
    mypy_django_plugin.main,
    mypy_drf_plugin.main

strict = False

disallow_untyped_defs = False
check_untyped_defs = True
warn_return_any = False
explicit_package_bases = True

ignore_missing_imports = True
follow_imports = silent

exclude = migrations|__pycache__|venv|env|.venv

[mypy.plugins.django-stubs]
django_settings_module = config.settings

[mypy-apps.*.models.*]
disallow_untyped_defs = False


; [mypy]
; python_version = 3.14


; plugins =
;     mypy_django_plugin.main,
;     mypy_drf_plugin.main

; strict = True

; disallow_untyped_defs = True
; check_untyped_defs = True
; warn_return_any = True
; explicit_package_bases = True

; ignore_missing_imports = True
; follow_imports = silent

; exclude = migrations|__pycache__|venv|env|.venv

; [mypy.plugins.django-stubs]
; django_settings_module = config.settings

; [mypy-apps.*.models.*]
; disallow_untyped_defs = False
