# Generated by Django 6.0.5 on 2026-06-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='skills_required',
        ),
        migrations.AddField(
            model_name='job',
            name='skills_required',
            field=models.ManyToManyField(blank=True, to='skill.skill'),
        ),
    ]
