# Generated by Django 6.0.6 on 2026-07-11 16:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_jobcategory_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='jobapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('job', 'applicant'), name='unique_active_job_application_per_applicant'),
        ),
    ]
