# Generated by Django 6.0.6 on 2026-08-01 17:45

import django.core.validators
from django.db import migrations, models


def clear_legacy_icon_names(apps, schema_editor):
    JobCategory = apps.get_model('jobs', 'JobCategory')
    JobCategory._base_manager.update(icon='')


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_unique_active_job_application_per_applicant'),
    ]

    operations = [
        migrations.RunPython(clear_legacy_icon_names, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='jobcategory',
            name='icon',
            field=models.FileField(blank=True, help_text='Custom SVG icon uploaded by admin', null=True, upload_to='job_category/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])]),
        ),
    ]
