# Generated by Django 6.0.6 on 2026-08-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_alter_jobapplication_status_job_job_created_at_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('under_review', 'Under Review'), ('interview_scheduled', 'Interview Scheduled'), ('interviewed', 'Interviewed'), ('offered', 'Offered'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('accepted', 'Accepted'), ('declined', 'Declined')], db_index=True, default='applied', max_length=20),
        ),
    ]
