# Generated by Django 6.0.5 on 2026-06-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='skills',
        ),
        migrations.AddField(
            model_name='service',
            name='skills',
            field=models.ManyToManyField(blank=True, to='skill.skill'),
        ),
    ]
