# Generated by Django 6.0.5 on 2026-06-27 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('services', '0003_remove_service_skills_service_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='locations.location'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='locations.location'),
        ),
    ]
