# Generated by Django 6.0.6 on 2026-07-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_service_available_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='color',
            field=models.CharField(blank=True, help_text='Optional color code in hex format (e.g., #RRGGBB)', max_length=10),
        ),
    ]
