# Generated by Django 6.0.6 on 2026-08-07 19:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('services', '0007_alter_servicecategory_icon'),
        ('skill', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['status', 'created_at'], name='service_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['status', 'created_at'], name='svcreq_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['status', 'completed_at'], name='svcreq_status_completed_idx'),
        ),
    ]
