# Generated by Django 6.0.6 on 2026-07-12 12:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('VIEW', 'View'), ('CLICK', 'Click'), ('SAVE', 'Save'), ('UNSAVE', 'Unsave'), ('APPLY', 'Apply'), ('REQUEST', 'Request'), ('SEARCH', 'Search')], max_length=20)),
                ('object_type', models.CharField(blank=True, choices=[('JOB', 'Job'), ('SERVICE', 'Service')], max_length=30)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='user_activi_user_id_ad1e3e_idx'), models.Index(fields=['object_type', 'object_id'], name='user_activi_object__0755df_idx'), models.Index(fields=['user', 'object_type', 'created_at'], name='user_activi_user_id_bacb85_idx')],
            },
        ),
    ]
