# Generated by Django 6.0.5 on 2026-05-29 12:36

import django.contrib.gis.db.models.fields
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('point', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('label', models.CharField(blank=True, help_text='e.g. Home, Office, Client location', max_length=50)),
                ('visibility_level', models.CharField(choices=[(0, 'Exact'), (1, 'Street'), (2, 'Area'), (3, 'City'), (4, 'State'), (5, 'Country'), (6, 'Hidden'), (7, 'Private')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
