# Generated by Django 6.0.5 on 2026-06-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_personalprofile_skills_personalprofile_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationprofile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='organizationprofile',
            name='organization_name',
        ),
        migrations.RemoveField(
            model_name='personalprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='personalprofile',
            name='profile_visibility',
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('limited', 'Limited')], default='public', max_length=20),
        ),
    ]
