# Generated by Django 6.0.5 on 2026-06-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_organizationprofile_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationprofile',
            name='social_links',
        ),
        migrations.RemoveField(
            model_name='personalprofile',
            name='social_links',
        ),
        migrations.AddField(
            model_name='user',
            name='social_links',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
