# Generated by Django 6.0.6 on 2026-08-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('locations', '0001_initial'),
        ('users', '0009_admin_roles_edit_removal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['account_type', 'date_joined'], name='user_accttype_joined_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['last_active_at'], name='user_last_active_idx'),
        ),
    ]
