# Generated by Django 6.0.6 on 2026-08-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_personalprofile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='new_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='otpverification',
            name='purpose',
            field=models.CharField(choices=[('signup', 'Signup'), ('change_email', 'Change Email'), ('delete_account', 'Delete Account')], default='signup', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='otpverification',
            constraint=models.UniqueConstraint(fields=('user', 'purpose'), name='unique_otp_per_user_purpose'),
        ),
    ]
