# Generated by Django 6.0.6 on 2026-08-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_personalprofile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
