# Generated by Django 6.0.6 on 2026-08-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_otpverification_new_email_otpverification_purpose_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE users_otpverification SET new_email = '' WHERE new_email IS NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='new_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
