# Generated by Django 6.0.6 on 2026-08-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_fix_new_email_not_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='purpose',
            field=models.CharField(choices=[('signup', 'Signup'), ('change_email', 'Change Email'), ('delete_account', 'Delete Account'), ('forgot_password', 'Forgot Password')], default='signup', max_length=20),
        ),
    ]
