# Generated by Django 6.0.6 on 2026-08-10 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_personalprofile_resume'),
        ('users', '0014_alter_otpverification_purpose'),
    ]

    operations = [
    ]
