# Generated by Django 6.0.6 on 2026-08-10 07:01

import apps.payment.models
import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0008_service_service_status_created_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('khalti', 'Khalti'), ('esewa', 'eSewa')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='NPR', max_length=3)),
                ('verified_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('initiated', 'Initiated'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('partially_refunded', 'Partially Refunded'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=25)),
                ('reference', models.CharField(db_index=True, default=apps.payment.models.generate_payment_reference, editable=False, max_length=50, unique=True)),
                ('transaction_id', models.CharField(blank=True, db_index=True, help_text='Internal NepWork transaction identifier.', max_length=255)),
                ('provider_transaction_id', models.CharField(blank=True, db_index=True, help_text='Transaction identifier returned by the payment provider.', max_length=255)),
                ('pidx', models.CharField(blank=True, db_index=True, help_text='Khalti payment identifier.', max_length=255)),
                ('esewa_transaction_uuid', models.CharField(blank=True, db_index=True, help_text='Transaction UUID sent to eSewa.', max_length=255)),
                ('esewa_ref_id', models.CharField(blank=True, db_index=True, help_text='Reference ID returned by eSewa.', max_length=255)),
                ('provider_response', models.JSONField(blank=True, default=dict, help_text='Response received when initiating payment.')),
                ('verification_response', models.JSONField(blank=True, default=dict, help_text='Response received when verifying payment.')),
                ('failure_reason', models.TextField(blank=True)),
                ('refund_reason', models.TextField(blank=True)),
                ('initiated_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='services.servicerequest')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'status'], name='payment_pay_provide_33dbc3_idx'), models.Index(fields=['order', 'status'], name='payment_pay_order_i_b37863_idx'), models.Index(fields=['created_at'], name='payment_pay_created_671024_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('pidx__gt', ''), ('provider', 'khalti')), fields=('pidx',), name='unique_khalti_pidx'), models.UniqueConstraint(condition=models.Q(('esewa_transaction_uuid__gt', ''), ('provider', 'esewa')), fields=('esewa_transaction_uuid',), name='unique_esewa_transaction_uuid'), models.CheckConstraint(condition=models.Q(('refunded_amount__gte', 0)), name='payment_refunded_amount_non_negative'), models.CheckConstraint(condition=models.Q(('verified_amount__gte', 0)), name='payment_verified_amount_non_negative')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
