# Generated by Django 6.0.6 on 2026-08-09 13:18

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0010_alter_jobapplication_status_job_job_created_at_idx_and_more'),
        ('services', '0008_service_service_status_created_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='jobs.job')),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='services.service')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['job'], name='reviews_rev_job_id_45562c_idx'), models.Index(fields=['service'], name='reviews_rev_service_1b4478_idx'), models.Index(fields=['reviewee'], name='reviews_rev_reviewe_57bac6_idx'), models.Index(fields=['reviewer'], name='reviews_rev_reviewe_e817a5_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('job__isnull', False), ('service__isnull', True)), models.Q(('job__isnull', True), ('service__isnull', False)), _connector='OR'), name='review_exactly_one_target'), models.CheckConstraint(condition=models.Q(('reviewer', models.F('reviewee')), _negated=True), name='reviewer_cannot_review_themselves'), models.UniqueConstraint(condition=models.Q(('job__isnull', False)), fields=('reviewer', 'job'), name='unique_review_per_reviewer_job'), models.UniqueConstraint(condition=models.Q(('service__isnull', False)), fields=('reviewer', 'service'), name='unique_review_per_reviewer_service')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
