# Generated by Django 6.0.6 on 2026-07-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_notification_action_url_notification_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('job_application_submitted', 'Job Application Submitted'), ('service_request_submitted', 'Service Request Submitted'), ('job_application_status_changed', 'Job Application Status Changed'), ('service_request_status_changed', 'Service Request Status Changed'), ('chat_message_received', 'Chat Message Received')], default='', max_length=50),
        ),
    ]
