# Generated by Django 6.0.6 on 2026-07-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_add_chat_message_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('job_application_submitted', 'Job Application Submitted'), ('service_request_submitted', 'Service Request Submitted'), ('job_application_status_changed', 'Job Application Status Changed'), ('service_request_status_changed', 'Service Request Status Changed')], default='', max_length=50),
        ),
    ]
