# Generated by Django 6.0.6 on 2026-07-17 14:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chat_type',
            field=models.CharField(choices=[('direct', 'Direct'), ('group', 'Group')], default='direct', max_length=10),
        ),
        migrations.AddField(
            model_name='chat',
            name='direct_pair_key',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', 'is_read'], name='chat_messag_chat_id_134fbf_idx'),
        ),
    ]
